export const STAGE_DETAILS = {
  1: {
    title: '기반 설정',
    goal: '프로젝트명, 상태, 담당자, 목표 일정을 확인하고 구축 기준을 고정합니다.',
    primaryLabel: '프로젝트 설정',
    primaryPath: (projectId) => `/admin/projects/${encodeURIComponent(projectId)}`,
    secondaryLabel: '프로젝트 목록',
    secondaryPath: () => '/admin/workflow/projects',
    tasks: ['고객사와 서비스 식별자 확인', '운영 상태와 담당자 확인', '목표 일정과 범위 메모 정리'],
  },
  2: {
    title: '지식 준비',
    goal: 'Source 등록, 벡터화 상태, 검색 테스트 결과를 기준으로 지식 기반을 준비합니다.',
    primaryLabel: 'Source 관리',
    primaryPath: () => '/admin/knowledge/sources',
    secondaryLabel: '검색 테스트',
    secondaryPath: () => '/admin/knowledge/search-test',
    tasks: ['Source 1건 이상 등록', '벡터화 완료 Source 확인', '대표 질문으로 검색 테스트 실행'],
  },
  3: {
    title: '의도 설계',
    goal: '대표 Intent와 Action 유형 초안을 등록해 챗봇이 질문 목적을 분류할 수 있게 합니다.',
    primaryLabel: 'Intent 관리',
    primaryPath: (projectId) => `/admin/intent-factory/intents?project=${encodeURIComponent(projectId)}`,
    secondaryLabel: 'LLM 보조 설계',
    secondaryPath: () => '/admin/intent-factory/llm-assist',
    tasks: ['대표 Intent 등록', '카테고리와 예시 질문 정리', 'Action 유형 초안 지정'],
  },
  4: {
    title: '질문 커버리지',
    goal: 'Intent별 예문을 보강해 실제 사용자 질문 변형을 충분히 커버합니다.',
    primaryLabel: 'Intent 상세',
    primaryPath: (projectId) => `/admin/intent-factory/intents?project=${encodeURIComponent(projectId)}`,
    secondaryLabel: 'FAQ 관리',
    secondaryPath: () => '/admin/intent-factory/faqs',
    tasks: ['Intent별 예문 수 점검', '누락된 표현 추가', '중복되거나 모호한 예문 정리'],
  },
  5: {
    title: '용어 사전',
    goal: '업무 용어와 동의어를 정리해 Intent 매칭과 Action 실행의 입력 품질을 높입니다.',
    primaryLabel: 'Entity 관리',
    primaryPath: () => '/admin/intent-factory/entities',
    secondaryLabel: 'Synonym 관리',
    secondaryPath: () => '/admin/intent-factory/synonyms',
    tasks: ['Entity 유형 등록', '동의어와 코드값 입력', '중복 용어 검토'],
  },
  6: {
    title: '답변 근거',
    goal: 'FAQ와 Source 근거를 연결해 답변이 운영 기준과 문서 근거를 갖도록 합니다.',
    primaryLabel: 'FAQ 관리',
    primaryPath: () => '/admin/intent-factory/faqs',
    secondaryLabel: '문서 Preview',
    secondaryPath: () => '/admin/knowledge/preview',
    tasks: ['FAQ 승인 대상 확정', '답변 근거 Source 연결', '근거 없는 답변 후보 분리'],
  },
  7: {
    title: '실행 연결',
    goal: 'Intent별 Action 연결과 단독 실행 테스트를 완료해 실제 업무 흐름으로 이어지게 합니다.',
    primaryLabel: 'Action 관리',
    primaryPath: () => '/admin/intent-factory/actions',
    secondaryLabel: 'Action 실행 테스트',
    secondaryPath: () => '/admin/runtime/action-test',
    tasks: ['미연결 Intent 확인', 'Action 파라미터 매핑', '대표 케이스 실행 테스트'],
  },
  8: {
    title: 'Pack 품질검증',
    goal: '필수 검증 질문을 실행하고 Pack 반영 전 품질 기준을 통과했는지 확인합니다.',
    primaryLabel: 'Pack 검증',
    primaryPath: () => '/admin/packs/validation',
    secondaryLabel: 'Pack Repository',
    secondaryPath: () => '/admin/packs/repository',
    tasks: ['검증 질문 세트 확인', '검증 실행', 'FAIL 항목의 원인 기록'],
  },
  9: {
    title: 'Runtime 시뮬레이션',
    goal: '대표 질문을 Runtime에서 실행해 Intent 매칭, 답변, Action 결과를 한 번에 검증합니다.',
    primaryLabel: 'Runtime QA',
    primaryPath: () => '/admin/runtime/qa',
    secondaryLabel: 'Intent 매칭 테스트',
    secondaryPath: () => '/admin/runtime/intent-match',
    tasks: ['대표 질문 시나리오 실행', 'Intent 매칭 결과 확인', 'Action 또는 답변 출력 검토'],
  },
  10: {
    title: 'Pack Build',
    goal: 'Export 전 검증을 통과한 Draft Pack을 생성하고 배포 가능한 산출물로 만듭니다.',
    primaryLabel: 'Pack Builder',
    primaryPath: () => '/admin/packs/builder',
    secondaryLabel: 'Pack 버전',
    secondaryPath: () => '/admin/packs/versions',
    tasks: ['Draft Pack 생성', 'Export 전 검증 결과 확인', 'ZIP 산출물 기록'],
  },
  11: {
    title: '배포/활성화',
    goal: '검증된 Pack을 승인하고 Active 전환 또는 Rollback 가능 상태로 운영에 반영합니다.',
    primaryLabel: 'Pack 배포',
    primaryPath: () => '/admin/packs/deployment',
    secondaryLabel: 'Pack Repository',
    secondaryPath: () => '/admin/packs/repository',
    tasks: ['Import 검증', '승인 또는 반려 처리', 'Active 전환 결과 확인'],
  },
  12: {
    title: '운영 분석/개선',
    goal: '미응답, 개선 요청, 운영 이력을 분석해 다음 Draft Pack 후보를 정리합니다.',
    primaryLabel: '미응답 분석',
    primaryPath: () => '/admin/operations/unanswered',
    secondaryLabel: '개선 요청',
    secondaryPath: () => '/admin/operations/improvement-requests',
    tasks: ['미응답 질문 분류', '개선 후보 우선순위 지정', 'Draft Pack 반영 후보 연결'],
  },
};
